# Cache downloaded dependencies and plugins between builds.
# Not strictly necessary, but speeds up the builds.
cache:
  key: "$CI_JOB_NAME"
  paths:
    # Must be within the repository under test hence we can't use the
    # default ~/.m2
    - .m2/repository
  

image: maven:latest # docker image with Maven
image: adoptopenjdk/openjdk18:latest


variables:
  # Use the cached directory above.
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

before_script:
  - ./setup-mvn-proxy.sh
  - chmod 400 $CI_SSH_KEY
  # Useful only for debugging
  #- cat ~/.m2/settings.xml

jobs:
  script:
    - export JAVA_HOME=/opt/java/openjdk
    - cd ./tp1
    - mvn clean compile --batch-mode -Dmaven.compiler.source=18 -Dmaven.compiler.target=18 --enable-preview
    - mvn clean package
    - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY ./target/todos.war gitlabci@192.168.75.47:8080/opt/tomcat/webapps/todos.war
